name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

   
      - name: Restore & Build app-dotnet
        run: |
          dotnet restore app-dotnet/app-dotnet.csproj
          dotnet build app-dotnet/app-dotnet.csproj -c Release --no-restore

      
      - name: Restore & Build LocalRunner
        run: |
          dotnet restore app-lambda-dotnet/LocalRunner/LocalRunner.csproj
          dotnet build app-lambda-dotnet/LocalRunner/LocalRunner.csproj -c Release --no-restore

     
      - name: Smoke test LocalRunner
        run: dotnet run --project app-lambda-dotnet/LocalRunner/LocalRunner.csproj
